### ISSUE TITLE
Issue while initializing an AuthClient instance

### ISSUE THREAD

**Issue by ksshetty** [okta/oktasdk-python#35]
The following error is seen while initializing an AuthClient object.
```>>> auth_client = AuthClient(base_url=base_url, api_token=api_key)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/shetty/work/django/pyenv/src/okta/okta/AuthClient.py", line 8, in __init__
    ApiClient.__init__(self, base_url + '/api/v1/authn', api_token)
  File "/Users/shetty/work/django/pyenv/src/okta/okta/framework/ApiClient.py", line 12, in __init__
    self.base_url = kwargs['base_url'] or args[0]
KeyError: 'base_url'```

**Comment by ksshetty** [comment]
I believe I have the fix for this issue. Looks like I do not have permissions to open a new Pull Request.

**Comment by jmelberg-okta** [comment]
@ksshetty: Thanks for raising this issue! We've [updated all of our clients](https://github.com/okta/oktasdk-python/pull/39) to account for the change in our new test suite.
