### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by PerGon** [okta/oktasdk-python#5]
Installing okta python sdk via pip, only fetches the files in the root folder (AppInstanceClient.py, AuthClient.py, etc.), the folders "framework" and "models" are not download, hence the okta python sdk won't work.

```
sudo pip install okta

python okta_python_test.py
Traceback (most recent call last):
  File "okta_python", line 2, in <module>
    from okta import AppInstanceClient
  File "/Library/Python/2.7/site-packages/okta/AppInstanceClient.py", line 1, in <module>
    from okta.framework.ApiClient import ApiClient
ImportError: No module named framework.ApiClient
```

This is how the python package looks after using `sudo pip install okta`:

```
ls -l /Library/Python/2.7/site-packages/okta
total 176
-rw-r--r--  1 root  wheel  1971 Sep  6 18:52 AppInstanceClient.py
-rw-r--r--  1 root  wheel  3241 Sep  6 18:52 AppInstanceClient.pyc
-rw-r--r--  1 root  wheel  6098 Sep  6 18:52 AuthClient.py
-rw-r--r--  1 root  wheel  6274 Sep  6 18:52 AuthClient.pyc
-rw-r--r--  1 root  wheel   759 Sep  6 18:52 EventsClient.py
-rw-r--r--  1 root  wheel  1448 Sep  6 18:52 EventsClient.pyc
-rw-r--r--  1 root  wheel  1016 Sep  6 18:52 FactorsAdminClient.py
-rw-r--r--  1 root  wheel  1836 Sep  6 18:52 FactorsAdminClient.pyc
-rw-r--r--  1 root  wheel  4285 Sep  6 18:52 FactorsClient.py
-rw-r--r--  1 root  wheel  5645 Sep  6 18:52 FactorsClient.pyc
-rw-r--r--  1 root  wheel  1716 Sep  6 18:52 SessionsClient.py
-rw-r--r--  1 root  wheel  2924 Sep  6 18:52 SessionsClient.pyc
-rw-r--r--  1 root  wheel  1533 Sep  6 18:52 UserGroupsClient.py
-rw-r--r--  1 root  wheel  2585 Sep  6 18:52 UserGroupsClient.pyc
-rw-r--r--  1 root  wheel  2843 Sep  6 18:52 UsersClient.py
-rw-r--r--  1 root  wheel  3997 Sep  6 18:52 UsersClient.pyc
-rw-r--r--  1 root  wheel    44 Sep  6 18:52 __init__.py
-rw-r--r--  1 root  wheel   168 Sep  6 18:52 __init__.pyc
```

If I manually download the folders "framework" and "models" and add them to "/Library/Python/2.7/site-packages/okta" everything works.

bonus: have a look at the pull requests and either accept them or send them back.

**Comment by jmelberg-okta** [comment]
Hi @PerGon. We apologize for the long delay.

We are currently in the process of updating this project. In the meantime, there is a proposed solution [described here](https://github.com/okta/oktasdk-python/issues/10). 

Thanks!

**Comment by jmelberg-okta** [comment]
Closing this issue as it was fixed in a previous release.
